"use client";

import { useState, useEffect } from "react";
import type { Locale } from "@/lib/i18n";

const STORAGE_KEY = "ai-super-app-locale";

function getStoredLocale(): Locale {
  if (typeof window === "undefined") return "ja";
  return (localStorage.getItem(STORAGE_KEY) as Locale) || "ja";
}

const content: Record<Locale, { title: string; lastUpdated: string; sections: { heading: string; body: string }[] }> = {
  ja: {
    title: "利用規約",
    lastUpdated: "最終更新日: 2026年2月15日",
    sections: [
      {
        heading: "1. サービスの概要",
        body: "AI Super App（以下「本サービス」）は、AI技術を活用した各種ツールを提供するアプリケーションです。本規約は、本サービスの利用に関する条件を定めるものです。",
      },
      {
        heading: "2. 利用条件",
        body: `• 本サービスの利用にあたり、本規約に同意いただく必要があります。
• 13歳未満の方はご利用いただけません。
• 無料プランでは1日あたりの利用回数に制限があります。
• プレミアムプランに加入すると、無制限で利用可能です。`,
      },
      {
        heading: "3. 禁止事項",
        body: `以下の行為は禁止されています。

• 違法行為または違法行為を助長する目的での利用
• 他者の権利を侵害するコンテンツの生成
• 本サービスのシステムに対する不正アクセスや攻撃
• レート制限を回避するための自動化されたアクセス
• 本サービスで生成したコンテンツを、AIが生成したことを隠して医療・法律アドバイスとして提供すること
• 本サービスの再販やリバースエンジニアリング`,
      },
      {
        heading: "4. AI生成コンテンツについて",
        body: `• 本サービスのAIツールが生成するコンテンツは参考情報であり、正確性を保証するものではありません。
• 医療、法律、財務に関するアドバイスは専門家にご相談ください。
• AI生成コンテンツに基づく判断や行動は、利用者自身の責任で行ってください。
• 画像生成機能で生成された画像の利用に関しては、各画像生成サービスの利用規約に従ってください。`,
      },
      {
        heading: "5. プレミアムプラン・課金について",
        body: `• プレミアムプランは月額制のサブスクリプションサービスです。
• Web版での決済はStripeを通じて処理されます。iOS版はApple、Android版はGoogle Playの各アプリ内課金を通じて処理されます。
• サブスクリプションは次回更新日の24時間前までにキャンセルしない限り自動更新されます。
• 返金については、各決済プラットフォームのポリシーに従います。`,
      },
      {
        heading: "6. 知的財産権",
        body: `• 本サービスのデザイン、ソースコード、ロゴ等の知的財産権は運営者に帰属します。
• 利用者がAIツールに入力したコンテンツの権利は利用者に帰属します。
• AIが生成したテキスト・画像のコンテンツは、利用規約の範囲内で自由にご利用いただけます。`,
      },
      {
        heading: "7. 免責事項",
        body: `• 本サービスは「現状有姿」で提供され、明示的または黙示的な保証は行いません。
• サービスの中断、データの損失、AI生成コンテンツの誤りによる損害について、運営者は責任を負いません。
• 第三者サービス（Anthropic、Together AI等）の障害に起因するサービス停止について、運営者は責任を負いません。`,
      },
      {
        heading: "8. 規約の変更",
        body: "運営者は、必要に応じて本規約を変更できるものとします。重要な変更がある場合は、アプリ内でお知らせします。変更後の規約は公開時点から効力を生じます。",
      },
      {
        heading: "9. 準拠法",
        body: "本規約の解釈および適用は、日本法に準拠するものとします。",
      },
      {
        heading: "10. お問い合わせ",
        body: "本規約に関するお問い合わせは、アプリ内のお問い合わせ機能またはメールにてご連絡ください。",
      },
    ],
  },
  en: {
    title: "Terms of Service",
    lastUpdated: "Last updated: February 15, 2026",
    sections: [
      {
        heading: "1. Service Overview",
        body: "AI Super App (\"the Service\") is an application that provides various AI-powered tools. These Terms govern your use of the Service.",
      },
      {
        heading: "2. Terms of Use",
        body: `• You must agree to these Terms to use the Service.
• Users under 13 years of age are not permitted to use the Service.
• The free plan has a daily usage limit.
• Premium plan subscribers get unlimited access.`,
      },
      {
        heading: "3. Prohibited Activities",
        body: `The following activities are prohibited:

• Using the Service for illegal purposes or to facilitate illegal activities
• Generating content that infringes on others' rights
• Unauthorized access or attacks on the Service's systems
• Automated access to circumvent rate limits
• Presenting AI-generated content as professional medical or legal advice without disclosure
• Reselling or reverse engineering the Service`,
      },
      {
        heading: "4. AI-Generated Content",
        body: `• Content generated by the Service's AI tools is for reference only and accuracy is not guaranteed.
• For medical, legal, or financial advice, please consult qualified professionals.
• Decisions and actions based on AI-generated content are the user's own responsibility.
• Use of images generated by the image generation feature is subject to the terms of the respective image generation services.`,
      },
      {
        heading: "5. Premium Plan & Billing",
        body: `• The Premium plan is a monthly subscription service.
• Web payments are processed through Stripe. iOS payments use Apple In-App Purchases, and Android payments use Google Play Billing.
• Subscriptions auto-renew unless cancelled at least 24 hours before the next renewal date.
• Refunds are subject to the policies of the respective payment platforms.`,
      },
      {
        heading: "6. Intellectual Property",
        body: `• Intellectual property rights for the Service's design, source code, and logos belong to the operator.
• Users retain rights to the content they input into AI tools.
• AI-generated text and image content may be freely used within the scope of these Terms.`,
      },
      {
        heading: "7. Disclaimer",
        body: `• The Service is provided "as is" without any express or implied warranties.
• The operator is not liable for damages resulting from service interruptions, data loss, or errors in AI-generated content.
• The operator is not liable for service outages caused by third-party service failures (Anthropic, Together AI, etc.).`,
      },
      {
        heading: "8. Changes to Terms",
        body: "The operator may modify these Terms as necessary. Significant changes will be communicated through the App. Modified Terms take effect upon publication.",
      },
      {
        heading: "9. Governing Law",
        body: "These Terms shall be governed by and construed in accordance with the laws of Japan.",
      },
      {
        heading: "10. Contact Us",
        body: "For inquiries regarding these Terms, please contact us through the in-app contact feature or email.",
      },
    ],
  },
  zh: {
    title: "使用条款",
    lastUpdated: "最后更新：2026年2月15日",
    sections: [
      {
        heading: "1. 服务概述",
        body: "AI Super App（以下简称\u201C本服务\u201D）是提供各种AI工具的应用程序。本条款规定了使用本服务的条件。",
      },
      {
        heading: "2. 使用条件",
        body: `• 使用本服务需同意本条款。
• 13岁以下用户禁止使用。
• 免费计划有每日使用次数限制。
• 订阅高级计划可无限使用。`,
      },
      {
        heading: "3. 禁止行为",
        body: `以下行为被禁止：

• 用于非法目的或促进非法活动
• 生成侵犯他人权利的内容
• 对本服务系统进行未授权访问或攻击
• 通过自动化手段绕过速率限制
• 将AI生成的内容伪装成专业医疗或法律建议
• 转售或逆向工程本服务`,
      },
      {
        heading: "4. AI生成内容",
        body: `• AI工具生成的内容仅供参考，不保证准确性。
• 医疗、法律或财务建议请咨询专业人士。
• 基于AI生成内容的决策和行为由用户自行负责。
• 图像生成功能生成的图像的使用须遵守各图像生成服务的条款。`,
      },
      {
        heading: "5. 高级计划与计费",
        body: `• 高级计划为月度订阅服务。
• 网页版支付通过Stripe处理。iOS版使用Apple应用内购买，Android版使用Google Play结算。
• 除非在下次续订日前24小时取消，否则订阅将自动续订。
• 退款遵循各支付平台的政策。`,
      },
      {
        heading: "6. 知识产权",
        body: `• 本服务的设计、源代码、标识等知识产权归运营者所有。
• 用户输入AI工具的内容权利归用户所有。
• AI生成的文本和图像内容可在本条款范围内自由使用。`,
      },
      {
        heading: "7. 免责声明",
        body: `• 本服务按"现状"提供，不提供任何明示或暗示的保证。
• 运营者不对服务中断、数据丢失或AI生成内容的错误造成的损害承担责任。
• 运营者不对第三方服务（Anthropic、Together AI等）故障导致的服务停止承担责任。`,
      },
      {
        heading: "8. 条款变更",
        body: "运营者可根据需要修改本条款。重大变更将通过应用内通知。修改后的条款自发布时生效。",
      },
      {
        heading: "9. 适用法律",
        body: "本条款的解释和适用以日本法律为准。",
      },
      {
        heading: "10. 联系我们",
        body: "有关本条款的咨询，请通过应用内联系功能或电子邮件与我们联系。",
      },
    ],
  },
  ko: {
    title: "이용약관",
    lastUpdated: "최종 업데이트: 2026년 2월 15일",
    sections: [
      {
        heading: "1. 서비스 개요",
        body: "AI Super App(이하 '본 서비스')은 다양한 AI 도구를 제공하는 애플리케이션입니다. 본 약관은 본 서비스의 이용 조건을 규정합니다.",
      },
      {
        heading: "2. 이용 조건",
        body: `• 본 서비스를 이용하려면 본 약관에 동의해야 합니다.
• 만 13세 미만은 이용할 수 없습니다.
• 무료 플랜은 일일 사용 횟수 제한이 있습니다.
• 프리미엄 플랜 가입 시 무제한 이용 가능합니다.`,
      },
      {
        heading: "3. 금지 행위",
        body: `다음 행위는 금지됩니다:

• 불법 목적 또는 불법 활동 촉진 목적의 이용
• 타인의 권리를 침해하는 콘텐츠 생성
• 본 서비스 시스템에 대한 무단 접근 또는 공격
• 속도 제한을 우회하기 위한 자동화된 접근
• AI 생성 콘텐츠를 전문 의료 또는 법률 조언으로 위장하여 제공
• 본 서비스의 재판매 또는 역공학`,
      },
      {
        heading: "4. AI 생성 콘텐츠",
        body: `• AI 도구가 생성하는 콘텐츠는 참고용이며 정확성을 보장하지 않습니다.
• 의료, 법률, 재무 조언은 전문가와 상담하세요.
• AI 생성 콘텐츠에 기반한 판단과 행동은 이용자 본인의 책임입니다.
• 이미지 생성 기능으로 생성된 이미지의 이용은 각 이미지 생성 서비스의 약관을 따릅니다.`,
      },
      {
        heading: "5. 프리미엄 플랜 및 결제",
        body: `• 프리미엄 플랜은 월간 구독 서비스입니다.
• 웹 결제는 Stripe를 통해 처리됩니다. iOS 결제는 Apple 인앱 결제, Android 결제는 Google Play 결제를 사용합니다.
• 다음 갱신일 24시간 전까지 취소하지 않으면 구독이 자동 갱신됩니다.
• 환불은 각 결제 플랫폼의 정책을 따릅니다.`,
      },
      {
        heading: "6. 지적 재산권",
        body: `• 본 서비스의 디자인, 소스 코드, 로고 등의 지적 재산권은 운영자에게 귀속됩니다.
• 이용자가 AI 도구에 입력한 콘텐츠의 권리는 이용자에게 귀속됩니다.
• AI가 생성한 텍스트 및 이미지 콘텐츠는 본 약관 범위 내에서 자유롭게 이용할 수 있습니다.`,
      },
      {
        heading: "7. 면책 조항",
        body: `• 본 서비스는 "있는 그대로" 제공되며 명시적 또는 묵시적 보증을 하지 않습니다.
• 운영자는 서비스 중단, 데이터 손실, AI 생성 콘텐츠의 오류로 인한 손해에 대해 책임을 지지 않습니다.
• 운영자는 제3자 서비스(Anthropic, Together AI 등)의 장애로 인한 서비스 중단에 대해 책임을 지지 않습니다.`,
      },
      {
        heading: "8. 약관 변경",
        body: "운영자는 필요에 따라 본 약관을 변경할 수 있습니다. 중요한 변경 사항은 앱 내에서 알려드립니다. 변경된 약관은 공개 시점부터 효력을 갖습니다.",
      },
      {
        heading: "9. 준거법",
        body: "본 약관의 해석 및 적용은 일본법에 따릅니다.",
      },
      {
        heading: "10. 문의",
        body: "본 약관에 관한 문의는 앱 내 문의 기능 또는 이메일로 연락해 주세요.",
      },
    ],
  },
};

export default function TermsPage() {
  const [locale, setLocale] = useState<Locale>("ja");

  useEffect(() => {
    setLocale(getStoredLocale());
  }, []);

  const c = content[locale];

  return (
    <main className="max-w-lg mx-auto px-6 py-10 min-h-screen">
      <a
        href="/"
        className="inline-flex items-center gap-1 text-sm text-blue-600 hover:text-blue-800 mb-6"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
        </svg>
        {locale === "ja" ? "ホームに戻る" : locale === "zh" ? "返回首页" : locale === "ko" ? "홈으로 돌아가기" : "Back to Home"}
      </a>
      <h1 className="text-2xl font-bold text-gray-900 mb-2">{c.title}</h1>
      <p className="text-xs text-gray-400 mb-8">{c.lastUpdated}</p>
      <div className="space-y-6">
        {c.sections.map((s, i) => (
          <section key={i}>
            <h2 className="text-base font-bold text-gray-800 mb-2">{s.heading}</h2>
            <p className="text-sm text-gray-600 leading-relaxed whitespace-pre-line">{s.body}</p>
          </section>
        ))}
      </div>
      <p className="text-center text-[10px] text-gray-300 mt-12 pb-8">AI Super App</p>
    </main>
  );
}
